package com.anvex.persistence;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public final class DatabaseManager {

    private static final Logger logger = LoggerFactory.getLogger(DatabaseManager.class);

    private static final String FILE_DB_URL = "jdbc:h2:file:./data/anvex;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;MODE=PostgreSQL";
    private static final String DB_USER = "sa";
    private static final String DB_PASSWORD = "";

    private static DatabaseManager instance;
    private final String dbUrl;

    private DatabaseManager(String url) {
        this.dbUrl = url;
    }

    public static synchronized DatabaseManager getInstance() {
        if (instance == null) {
            instance = new DatabaseManager(FILE_DB_URL);
        }
        return instance;
    }

    public static synchronized DatabaseManager getTestInstance() {
        if (instance == null) {
            instance = new DatabaseManager("jdbc:h2:mem:anvex_test_" + java.util.UUID.randomUUID()
                    + ";DB_CLOSE_DELAY=-1;MODE=PostgreSQL");
        }
        return instance;
    }

    public static synchronized DatabaseManager getFileInstance(String filePath) {
        if (instance == null) instance = new DatabaseManager("jdbc:h2:file:" + filePath + ";AUTO_SERVER=TRUE;MODE=PostgreSQL");
        return instance;
    }

    public static synchronized void resetInstance() {
        if (instance != null) {
            instance.shutdown();
            instance = null;
        }
    }

    public Connection getConnection() throws SQLException {
        Connection conn = DriverManager.getConnection(dbUrl, DB_USER, DB_PASSWORD);
        logger.debug("New H2 connection established: {}", dbUrl);
        return conn;
    }

    public long lastEventSequence() throws SQLException {
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT COALESCE(MAX(sequence_no),0) FROM security_events")) {
            rs.next(); return rs.getLong(1);
        }
    }

    public void initialize() throws SQLException {
        logger.info("Initializing H2 database: {}", dbUrl);
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()) {

            // Users table
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(100) NOT NULL UNIQUE,
                    password_hash VARCHAR(255) NOT NULL,
                    role VARCHAR(50) NOT NULL,
                    enabled BOOLEAN DEFAULT TRUE,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """);
            logger.info("Created USERS table");

            // Scenario runs table
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS scenario_runs (
                    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_label VARCHAR(100) NOT NULL,
                    defense_enabled BOOLEAN NOT NULL,
                    start_time TIMESTAMP NOT NULL,
                    end_time TIMESTAMP,
                    status VARCHAR(50) DEFAULT 'RUNNING',
                    persistence_status VARCHAR(50) DEFAULT 'PENDING'
                )
                """);
            logger.info("Created SCENARIO_RUNS table");

            // Security events table
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS security_events (
                    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sequence_no BIGINT NOT NULL,
                    run_id BIGINT NOT NULL,
                    timestamp TIMESTAMP NOT NULL,
                    event_type VARCHAR(50) NOT NULL,
                    username VARCHAR(100),
                    client_type VARCHAR(50),
                    source VARCHAR(100),
                    outcome VARCHAR(50),
                    threat_level VARCHAR(20),
                    threat_score INT,
                    metadata VARCHAR(2000),
                    evidence_failed_attempts BIGINT,
                    evidence_window_ms BIGINT,
                    evidence_frequency DOUBLE,
                    evidence_threshold_exceeded BOOLEAN,
                    message VARCHAR(500)
                )
                """);
            stmt.execute("ALTER TABLE security_events ADD COLUMN IF NOT EXISTS threat_score INT");
            stmt.execute("ALTER TABLE security_events ADD COLUMN IF NOT EXISTS metadata VARCHAR(2000)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_security_events_run_id ON security_events(run_id)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_security_events_sequence ON security_events(sequence_no)");
            logger.info("Created SECURITY_EVENTS table");

            // Alerts table
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS alerts (
                    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_id BIGINT NOT NULL,
                    rule_id VARCHAR(100) NOT NULL,
                    severity VARCHAR(20) NOT NULL,
                    timestamp TIMESTAMP NOT NULL,
                    username VARCHAR(100),
                    explanation VARCHAR(500)
                )
                """);
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_alerts_run_id ON alerts(run_id)");
            logger.info("Created ALERTS table");

            // Metrics snapshots table
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS metrics_snapshots (
                    run_id BIGINT PRIMARY KEY,
                    total_attempts BIGINT DEFAULT 0,
                    failures BIGINT DEFAULT 0,
                    blocked BIGINT DEFAULT 0,
                    attacker_success BIGINT DEFAULT 0,
                    legitimate_success BIGINT DEFAULT 0,
                    compromised BOOLEAN DEFAULT FALSE,
                    duration_ms BIGINT DEFAULT 0
                )
                """);
            logger.info("Created METRICS_SNAPSHOTS table");

            // Comparison results table
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS comparison_results (
                    comparison_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    before_run_id BIGINT NOT NULL,
                    after_run_id BIGINT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """);
            logger.info("Created COMPARISON_RESULTS table");

            // Verify tables exist
            try (ResultSet rs = conn.getMetaData().getTables(null, null, "USERS", null)) {
                if (rs.next()) {
                    logger.info("VERIFIED: USERS table exists");
                } else {
                    logger.error("USERS table NOT FOUND after creation!");
                }
            }

            logger.info("Database initialized successfully");
        } catch (SQLException e) {
            logger.error("Database initialization failed", e);
            throw e;
        }
    }

    public void shutdown() {
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("SHUTDOWN");
        } catch (SQLException e) {
            logger.warn("Database shutdown reported an error: {}", e.getMessage());
        }
        logger.info("Database manager shut down: {}", dbUrl);
    }
}
