package com.anvex.persistence;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public final class DatabaseManager {

    private static final Logger logger = LoggerFactory.getLogger(DatabaseManager.class);

    private static final String TEST_DB_URL = "jdbc:h2:mem:anvex_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL";
    private static final String FILE_DB_URL = "jdbc:h2:file:./data/anvex;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;MODE=PostgreSQL";
    private static final String DB_USER = "sa";
    private static final String DB_PASSWORD = "";

    private static DatabaseManager testInstance;
    private static DatabaseManager fileInstance;
    private Connection connection;
    private final String dbUrl;

    private DatabaseManager(boolean testMode) {
        this.dbUrl = testMode ? TEST_DB_URL : FILE_DB_URL;
    }

    public static synchronized DatabaseManager getInstance() {
        if (fileInstance == null) {
            fileInstance = new DatabaseManager(false);
        }
        return fileInstance;
    }

    public static synchronized DatabaseManager getTestInstance() {
        // Always create fresh instance for tests
        if (testInstance != null) {
            testInstance.shutdown();
        }
        testInstance = new DatabaseManager(true);
        return testInstance;
    }

    public static synchronized void resetInstance() {
        if (testInstance != null) {
            testInstance.shutdown();
            testInstance = null;
        }
        if (fileInstance != null) {
            fileInstance.shutdown();
            fileInstance = null;
        }
    }

    public Connection getConnection() throws SQLException {
        if (connection == null || connection.isClosed()) {
            connection = DriverManager.getConnection(dbUrl, DB_USER, DB_PASSWORD);
            logger.debug("New H2 connection established: {}", dbUrl);
        }
        return connection;
    }

    public void initialize() throws SQLException {
        logger.info("Initializing H2 database: {}", dbUrl);
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()) {

            stmt.execute("DROP TABLE IF EXISTS comparison_results");
            stmt.execute("DROP TABLE IF EXISTS metrics_snapshots");
            stmt.execute("DROP TABLE IF EXISTS alerts");
            stmt.execute("DROP TABLE IF EXISTS security_events");
            stmt.execute("DROP TABLE IF EXISTS scenario_runs");
            stmt.execute("DROP TABLE IF EXISTS users");
            logger.info("Dropped existing tables");

            stmt.execute("""
                CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(100) NOT NULL UNIQUE,
                    password_hash VARCHAR(255) NOT NULL,
                    role VARCHAR(50) NOT NULL,
                    enabled BOOLEAN DEFAULT TRUE,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """);
            logger.info("Created USERS table");

            stmt.execute("""
                CREATE TABLE scenario_runs (
                    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_label VARCHAR(100) NOT NULL,
                    defense_enabled BOOLEAN NOT NULL,
                    start_time TIMESTAMP NOT NULL,
                    end_time TIMESTAMP,
                    status VARCHAR(50) DEFAULT 'RUNNING',
                    persistence_status VARCHAR(50) DEFAULT 'PENDING'
                )
                """);
            logger.info("Created SCENARIO_RUNS table");

            stmt.execute("""
                CREATE TABLE security_events (
                    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sequence_no BIGINT NOT NULL,
                    run_id BIGINT NOT NULL,
                    timestamp TIMESTAMP NOT NULL,
                    event_type VARCHAR(50) NOT NULL,
                    username VARCHAR(100),
                    client_type VARCHAR(50),
                    message VARCHAR(500)
                )
                """);
            stmt.execute("CREATE INDEX idx_security_events_run_id ON security_events(run_id)");
            stmt.execute("CREATE INDEX idx_security_events_sequence ON security_events(sequence_no)");
            logger.info("Created SECURITY_EVENTS table");

            stmt.execute("""
                CREATE TABLE alerts (
                    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_id BIGINT NOT NULL,
                    rule_id VARCHAR(100) NOT NULL,
                    severity VARCHAR(20) NOT NULL,
                    timestamp TIMESTAMP NOT NULL,
                    username VARCHAR(100),
                    explanation VARCHAR(500)
                )
                """);
            stmt.execute("CREATE INDEX idx_alerts_run_id ON alerts(run_id)");
            logger.info("Created ALERTS table");

            stmt.execute("""
                CREATE TABLE metrics_snapshots (
                    run_id BIGINT PRIMARY KEY,
                    total_attempts BIGINT DEFAULT 0,
                    failures BIGINT DEFAULT 0,
                    blocked BIGINT DEFAULT 0,
                    attacker_success BIGINT DEFAULT 0,
                    legitimate_success BIGINT DEFAULT 0,
                    compromised BOOLEAN DEFAULT FALSE,
                    duration_ms BIGINT DEFAULT 0
                )
                """);
            logger.info("Created METRICS_SNAPSHOTS table");

            stmt.execute("""
                CREATE TABLE comparison_results (
                    comparison_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    before_run_id BIGINT NOT NULL,
                    after_run_id BIGINT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """);
            logger.info("Created COMPARISON_RESULTS table");

            try (ResultSet rs = conn.getMetaData().getTables(null, null, "USERS", null)) {
                if (rs.next()) {
                    logger.info("VERIFIED: USERS table exists");
                } else {
                    logger.error("USERS table NOT FOUND after creation!");
                }
            }

            logger.info("Database initialized successfully");
        } catch (SQLException e) {
            logger.error("Database initialization failed", e);
            throw e;
        }
    }

    public void shutdown() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
                logger.info("Database connection closed");
            }
        } catch (SQLException e) {
            logger.error("Error closing database", e);
        }
    }
}
