import { useMemo, useState } from 'react'
import Tabs from '../../components/Tabs.jsx'
import { useLab } from '../lab-context.jsx'
import './event-payload-preview.css'

const TABS = ['REQUEST', 'JSON', 'RAW']

const VARIABLES = [
  { key: 'username', label: 'Target user' },
  { key: 'password', label: 'Password pattern' },
  { key: 'clientType', label: 'Client type' },
  { key: 'sourceId', label: 'Source identity id' }
]

export default function EventPayloadPreview() {
  const { config, safety, sanitize } = useLab()
  const [tab, setTab] = useState('REQUEST')

  const attemptNumber = Number(config.attempts) || 1
  const payload = useMemo(() => ({
    username: safety.payloadSanitization ? sanitize(config.targetUser) : config.targetUser,
    'password': `wrong-guess-1 … wrong-guess-${attemptNumber}`,
    clientType: 'ATTACKER',
    sourceId: safety.payloadSanitization ? sanitize(config.sourceId) : config.sourceId
  }), [config, safety, sanitize, attemptNumber])

  const json = JSON.stringify({
    username: payload.username,
    password: 'wrong-guess-1',
    clientType: 'ATTACKER',
    sourceId: payload.sourceId
  }, null, 2)
  const raw = JSON.stringify({
    username: payload.username,
    password: 'wrong-guess-1',
    clientType: 'ATTACKER',
    sourceId: payload.sourceId
  })

  return (
    <div className="payload-preview">
      <div className="payload-main">
        <div className="payload-head">
          <Tabs tabs={TABS} active={tab} onChange={setTab} />
        </div>
        {tab === 'REQUEST' && (
          <div className="payload-rows">
            <div className="payload-request-row">
              <span className="payload-request-key">username</span>
              <span className="payload-request-value">{payload.username || '—'}</span>
            </div>
            <div className="payload-request-row">
              <span className="payload-request-key">password</span>
              <span className="payload-request-value">{payload['password']}</span>
            </div>
            <div className="payload-request-row">
              <span className="payload-request-key">clientType</span>
              <span className="payload-request-value">{payload.clientType}</span>
            </div>
            <div className="payload-request-row">
              <span className="payload-request-key">sourceId</span>
              <span className="payload-request-value">{payload.sourceId || '—'}</span>
            </div>
          </div>
        )}
        {tab === 'JSON' && <pre className="payload-json">{json}</pre>}
        {tab === 'RAW' && <pre className="payload-json payload-raw">{raw}</pre>}
        <p className="payload-note">
          This is exactly what the browser sends per attempt to the ANVEX lab authentication service.
          Security events, outcomes, threat levels and protection decisions are generated by the ANVEX
          Java backend — the browser does not send Windows events, OS data or network packets.
        </p>
      </div>
      <aside className="payload-variables">
        <span className="payload-variables-title">VARIABLES</span>
        <div className="payload-variable-list">
          {VARIABLES.map((v) => {
            const resolved = {
              username: payload.username,
              'password': 'wrong-guess-N',
              clientType: payload.clientType,
              sourceId: payload.sourceId
            }[v.key]
            return (
              <div key={v.key} className="payload-variable">
                <span className="payload-variable-key">{`{{${v.key}}}`}</span>
                <span className="payload-variable-value">{String(resolved)}</span>
              </div>
            )
          })}
        </div>
        {safety.payloadSanitization && (
          <p className="payload-sanitized-note">Sanitization ON: | , CR and LF stripped from inputs.</p>
        )}
      </aside>
    </div>
  )
}
