import { useMemo, useState } from 'react'
import Tabs from '../../components/Tabs.jsx'
import DiagnosticRow from '../../components/DiagnosticRow.jsx'
import { useLab } from '../lab-context.jsx'
import './event-payload-preview.css'

const TABS = ['EVENT PREVIEW', 'JSON', 'RAW']

const VARIABLES = [
  { key: 'sourceId', label: 'Source identity id' },
  { key: 'sourceIp', label: 'Source identity IP' },
  { key: 'username', label: 'Target user' },
  { key: 'targetService', label: 'Target service' },
  { key: 'attempts', label: 'Attempt count' },
  { key: 'interval', label: 'Attempt interval (s)' }
]

export default function EventPayloadPreview() {
  const { config, sources } = useLab()
  const [tab, setTab] = useState('EVENT PREVIEW')

  const source = sources.find((s) => s.id === config.sourceId)
  const preview = useMemo(() => ({
    eventType: 'LOGIN_FAILURE (Event 4625)',
    source: 'ANVEX-LabSimulator',
    sourceId: config.sourceId,
    sourceIp: source ? source.ip : 'unknown',
    target: config.sourceId,
    service: 'ANVEX-Core Authentication',
    user: config.targetUser,
    clientType: 'ATTACKER',
    loginType: 'INTERACTIVE',
    timestamp: '{{timestamp}}',
    message: 'An account failed to log on.'
  }), [config, source])

  const requestPayload = useMemo(() => ({
    username: config.targetUser,
    password: 'wrong-guess-N',
    clientType: 'ATTACKER',
    sourceId: config.sourceId
  }), [config])

  const json = JSON.stringify(requestPayload, null, 2)
  const raw = JSON.stringify(requestPayload)

  return (
    <div className="payload-preview">
      <div className="payload-main">
        <div className="payload-head">
          <Tabs tabs={TABS} active={tab} onChange={setTab} />
        </div>
        {tab === 'EVENT PREVIEW' && (
          <div className="payload-rows">
            <DiagnosticRow label="eventType" value={preview.eventType} accent="cyan" />
            <DiagnosticRow label="source" value={preview.source} />
            <DiagnosticRow label="sourceId" value={preview.sourceId} />
            <DiagnosticRow label="sourceIp" value={preview.sourceIp} />
            <DiagnosticRow label="target" value={preview.target} />
            <DiagnosticRow label="service" value={preview.service} />
            <DiagnosticRow label="user" value={preview.user} />
            <DiagnosticRow label="clientType" value={preview.clientType} accent="orange" />
            <DiagnosticRow label="loginType" value={preview.loginType} />
            <DiagnosticRow label="timestamp" value={preview.timestamp} accent="muted" />
            <DiagnosticRow label="message" value={preview.message} />
          </div>
        )}
        {tab === 'JSON' && <pre className="payload-json">{json}</pre>}
        {tab === 'RAW' && <pre className="payload-json payload-raw">{raw}</pre>}
        <p className="payload-note">
          Preview derived from the current simulation configuration. Actual outcomes are generated by the ANVEX
          backend and appear in the simulation log.
        </p>
      </div>
      <aside className="payload-variables">
        <span className="payload-variables-title">VARIABLES</span>
        <div className="payload-variable-list">
          {VARIABLES.map((v) => {
            const resolved = {
              sourceId: config.sourceId,
              sourceIp: source ? source.ip : 'unknown',
              username: config.targetUser,
              targetService: 'ANVEX-Core Authentication',
              attempts: config.attempts,
              interval: config.interval
            }[v.key]
            return (
              <div key={v.key} className="payload-variable">
                <span className="payload-variable-key">{`{{${v.key}}}`}</span>
                <span className="payload-variable-value">{String(resolved)}</span>
              </div>
            )
          })}
        </div>
      </aside>
    </div>
  )
}
